# version: 2.1
orbs:
  browser-tools: circleci/browser-tools@x.y
jobs:
  build:
    docker:
      - image: cimg/node:20.11.0-browsers  
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm install --save-dev nightwatch@1.7.2
      - run: npm install chromedriver --save-dev
      - run: npx nightwatch -e chrome
