version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  build:
    docker:
      - image: cimg/node:20.11.0-browsers  
    steps:
      - checkout
      - run: npm install --save-dev nightwatch@1.7.2
      - run: npm install chromedriver --save-dev
      - run: npx nightwatch -e chrome

