# version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
  
    steps:
      - checkout
      - run: npm install --save-dev nightwatch@1.7.2
      - run: npm install chromedriver --save-dev
