version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@x.y
jobs:
  test:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
workflows: null
